# This file was generated by GoReleaser. DO NOT EDIT.
cask "aitinerary" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "930c9d15ff9897011b108636bed555a537151102e59e62614064b26e348db38f"
      url "https://github.com/madicen/aitinerary/releases/download/v#{version}/aitinerary_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "af00e6a93ed062f55e76c0f2776c0e877e6178f8af83488c096059677c4d1ade"
      url "https://github.com/madicen/aitinerary/releases/download/v#{version}/aitinerary_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "33900855ff97835e3fcb89ebbce3a6b81a9c8a2c707e317ff781c008d25d0023"
      url "https://github.com/madicen/aitinerary/releases/download/v#{version}/aitinerary_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1eddca59d08a623ce6cf68c0213fa5e726e2be2aece4757f8549805f024caf3a"
      url "https://github.com/madicen/aitinerary/releases/download/v#{version}/aitinerary_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aitinerary"
  desc "A BubbleTea TUI for Jira ticket hygiene"
  homepage "https://github.com/madicen/aitinerary"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "aitinerary"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aitinerary"]
    end
  end

  # No zap stanza required

end
