# This file was generated by GoReleaser. DO NOT EDIT.
cask "appr-ai-sal" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "221ccd18c71ecfe238286fcec3966c2f5792ed9cc8a3c8957a944e07a930bd85"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "acac589d84d1192c7f48802edceb4019394f685ff0cc34f73308c7182d3862f3"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "16b6d76bb8e248e9e2a6d7f881156b088aebcfc57a568ef974cf1a093e9d7999"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b3dcd9f89f6075f0e7e2ac08dde702a9bf17f55a2b7d29a3536dad04b042489"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "appr-ai-sal"
  desc "Specialist AI code reviews for your GitHub PRs, in the terminal"
  homepage "https://github.com/madicen/appr-ai-sal"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "appr-ai-sal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/appr-ai-sal"]
    end
  end

  # No zap stanza required

end
