# This file was generated by GoReleaser. DO NOT EDIT.
cask "appr-ai-sal" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "cf157fe6f61b1a4034e673a7bebdf8d7da9a5f7a284d7c54617560c6ba5f9c82"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "96c7771b0c46f809b99948216918704a383d7698535edd0fb397b593f6485d06"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b29d33029ed70a5a60dad8d2ee3f7744a1d5a5f676659d23c42f5bf6b1548c73"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7a9f60fc81cc1fe6229c7d79de9b87643744d5d2ab68b2726ece305bd39fde5"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "appr-ai-sal"
  desc "Specialist AI code reviews for your GitHub PRs, in the terminal"
  homepage "https://github.com/madicen/appr-ai-sal"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "appr-ai-sal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/appr-ai-sal"]
    end
  end

  # No zap stanza required

end
