# This file was generated by GoReleaser. DO NOT EDIT.
cask "appr-ai-sal" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "b5faeadab31f398696293f6b87e95c209596232dc1ecb59121c82800ce0f68d0"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb2ab3acdc6f027ed0845b916294716380c33e21c694c5b31bfea02c82849f77"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3388a79fe27b297738eb74a606a8f202509c1b9cf309b274cbe1a4e74f16bf06"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "39eedce97166466be9e81315818b7f0cf1581339f22c37d387df72d98c3ee23a"
      url "https://github.com/madicen/appr-ai-sal/releases/download/v#{version}/appr-ai-sal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "appr-ai-sal"
  desc "Specialist AI code reviews for your GitHub PRs, in the terminal"
  homepage "https://github.com/madicen/appr-ai-sal"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "appr-ai-sal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/appr-ai-sal"]
    end
  end

  # No zap stanza required

end
