# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-tui" do
  version "0.8.4"

  on_macos do
    on_intel do
      sha256 "4ddbaac98df84b3b953861cf7b6722fbe3578a2352ce5a8f813086761ab81697"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1843895aede9dc99d4c1eb7cb4e9377799db3ef3d215ceb001e4a755796bd31"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3947bc8d9c1ba9425c7a7fb8555c1f4a098e54115058744c4cff9cce15532c6b"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "adac7ed32508fb60792f9e8f6154d0eb15a68f9d8c7e4dae7ae0b548cdbe7f5f"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jj-tui"
  desc "A modern Terminal User Interface for managing Jujutsu repositories"
  homepage "https://github.com/madicen/jj-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jj-tui"]
    end
  end

  # No zap stanza required

end
