# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-tui" do
  version "0.7.5"

  on_macos do
    on_intel do
      sha256 "48373108e07fdf60cb6c200d139ef50dcf875bf7418c9751e3d3995e06fc83af"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e41297d228e93dec5392ff514712d4e7fcd6741b48382008810359039c7bbb57"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f461fed8bebdd8fe75ae4526d01c6e2c249b58ab8160b759ad5e3e090e4f45b"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "12c65917b068318ae32e57710a3e7bbc6b34514c10b16c4b03f2662ce39a322a"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jj-tui"
  desc "A modern Terminal User Interface for managing Jujutsu repositories"
  homepage "https://github.com/madicen/jj-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jj-tui"]
    end
  end

  # No zap stanza required

end
