# This file was generated by GoReleaser. DO NOT EDIT.
cask "jj-tui" do
  version "0.7.18"

  on_macos do
    on_intel do
      sha256 "9c3a2eacb6b6105b3d4c85afa861cf17b159004f6bac1460c5ef2236033dfa08"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c17e736af55469ea91412714591e1680503371b9d5ae1157c7d9978b0f8fbc3b"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "48ff1ea5ee5d4fdb12d8b9048d1846a21cd6b26f9af7f4245a1c2a80e289e394"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0344a7bc68bcdc5596ff5a1c038cbc08e2f9c17e8fda68ac4772fc679d6c362"
      url "https://github.com/madicen/jj-tui/releases/download/v#{version}/jj-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jj-tui"
  desc "A modern Terminal User Interface for managing Jujutsu repositories"
  homepage "https://github.com/madicen/jj-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jj-tui"]
    end
  end

  # No zap stanza required

end
