# This file was generated by GoReleaser. DO NOT EDIT.
cask "naitv-mcp" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "08a57c72d5297efb1c1e7a67cf50de7afd20ae3d68cd01e8ef560974d4de794b"
      url "https://github.com/madicen/naitv-mcp/releases/download/v#{version}/naitv-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "73b197ff92f30d12ca96e688911561c0c660f36156f47a3018c5068795ec4850"
      url "https://github.com/madicen/naitv-mcp/releases/download/v#{version}/naitv-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dbece67dedb430545bf3108b8c2d045acc3448f550110ef3f472a58bbf86f1bf"
      url "https://github.com/madicen/naitv-mcp/releases/download/v#{version}/naitv-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "79564509a4e7079baf52594e26d59090d374a85185ee288a60ffa1dfa72e4707"
      url "https://github.com/madicen/naitv-mcp/releases/download/v#{version}/naitv-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "naitv-mcp"
  desc "Local MCP server + TUI for managing AI agent context"
  homepage "https://github.com/madicen/naitv-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "naitv-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/naitv-mcp"]
    end
  end

  # No zap stanza required

end
