# This file was generated by GoReleaser. DO NOT EDIT.
cask "naitv-mcp" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "3b3b9e95656c7b07bcfef6741613e4a4c2128e63e6f5c137fa7dab94803b4af5"
      url "https://github.com/madicen/naitv-mcp/releases/download/v#{version}/naitv-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9171455d634c3734f84d006ab16a45f4eba7a1e5509436a1ad036deebaa38e6"
      url "https://github.com/madicen/naitv-mcp/releases/download/v#{version}/naitv-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d4f87919bfef06f5f049b325bcdc7a14ca027c9a5ec00fb75a4975395dd40a9"
      url "https://github.com/madicen/naitv-mcp/releases/download/v#{version}/naitv-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d64a210396f65e52194e072fa62acd10c3fb2dd083cde494e79ff22fcf9ad485"
      url "https://github.com/madicen/naitv-mcp/releases/download/v#{version}/naitv-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "naitv-mcp"
  desc "Local MCP server + TUI for managing AI agent context"
  homepage "https://github.com/madicen/naitv-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "naitv-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/naitv-mcp"]
    end
  end
  generate_completions_from_executable "naitv-mcp", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
