# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JjTui < Formula
  desc "A modern Terminal User Interface for managing Jujutsu repositories"
  homepage "https://github.com/madicen/jj-tui"
  version "0.6.8"
  license "MIT"

  depends_on "jj" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madicen/jj-tui/releases/download/v0.6.8/jj-tui_0.6.8_darwin_amd64.tar.gz"
      sha256 "15b78b9dada3dc0d41e2e863d78b86945a40b3207fde83caf2211d5463667e50"

      define_method(:install) do
        bin.install "jj-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madicen/jj-tui/releases/download/v0.6.8/jj-tui_0.6.8_darwin_arm64.tar.gz"
      sha256 "c45f6b7b998d21803eac86890f813c9cdf17123e6702659a869e8c3236cd267c"

      define_method(:install) do
        bin.install "jj-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madicen/jj-tui/releases/download/v0.6.8/jj-tui_0.6.8_linux_amd64.tar.gz"
      sha256 "5fc948aa71cb927fee8722fd1e72c10ee38058f25593e20d285ac742902f41dd"
      define_method(:install) do
        bin.install "jj-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madicen/jj-tui/releases/download/v0.6.8/jj-tui_0.6.8_linux_arm64.tar.gz"
      sha256 "4b9739219cc42d3a5614e692b469b9d154d53119d88f3763b40d4b3e21a34a7f"
      define_method(:install) do
        bin.install "jj-tui"
      end
    end
  end

  test do
    system "#{bin}/jj-tui", "--help"
  end
end
