# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JjTui < Formula
  desc "A modern Terminal User Interface for managing Jujutsu repositories"
  homepage "https://github.com/madicen/jj-tui"
  version "0.4.4"
  license "MIT"

  depends_on "jj" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madicen/jj-tui/releases/download/v0.4.4/jj-tui_0.4.4_darwin_amd64.tar.gz"
      sha256 "3a4de8d1920417b18eed8d9dc77f3acf37490b1188b4849e6d7371b2dea67de7"

      define_method(:install) do
        bin.install "jj-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madicen/jj-tui/releases/download/v0.4.4/jj-tui_0.4.4_darwin_arm64.tar.gz"
      sha256 "1cf503d3fa98aed8edcb88da9d181f481e0f4c49d25b2577f150d7cda1dfcc43"

      define_method(:install) do
        bin.install "jj-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madicen/jj-tui/releases/download/v0.4.4/jj-tui_0.4.4_linux_amd64.tar.gz"
      sha256 "ef6f14ecc9012ad05b91ec1f63b9a71edb45ab4a9a5b6fecca3fea0b63976fcc"
      define_method(:install) do
        bin.install "jj-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madicen/jj-tui/releases/download/v0.4.4/jj-tui_0.4.4_linux_arm64.tar.gz"
      sha256 "236f3b324afc920b573b48f9b28d7a298f9554405998065d01e9bfcd063f9f7a"
      define_method(:install) do
        bin.install "jj-tui"
      end
    end
  end

  test do
    system "#{bin}/jj-tui", "--help"
  end
end
