# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JjTui < Formula
  desc "A modern Terminal User Interface for managing Jujutsu repositories"
  homepage "https://github.com/madicen/jj-tui"
  version "0.2.2"
  license "MIT"

  depends_on "jj" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madicen/jj-tui/releases/download/v0.2.2/jj-tui_0.2.2_darwin_amd64.tar.gz"
      sha256 "788fff47a73b2b0fb40d9108af28e6b016651a34a0fbaa64e3307c9668658762"

      def install
        bin.install "jj-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madicen/jj-tui/releases/download/v0.2.2/jj-tui_0.2.2_darwin_arm64.tar.gz"
      sha256 "1a6bec9e9ccd36970ff244c298779ac3d44b9cfb142fa34407785a100d1c3530"

      def install
        bin.install "jj-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madicen/jj-tui/releases/download/v0.2.2/jj-tui_0.2.2_linux_amd64.tar.gz"
      sha256 "d79f74356eee9b04a861d73a9ef935dee9c2d925c3a27f05c7936789b0a8f569"
      def install
        bin.install "jj-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madicen/jj-tui/releases/download/v0.2.2/jj-tui_0.2.2_linux_arm64.tar.gz"
      sha256 "36b43774936b106a5b25c627d75a358366f0c5fa7b72c2bf40742b63df742048"
      def install
        bin.install "jj-tui"
      end
    end
  end

  test do
    system "#{bin}/jj-tui", "--help"
  end
end
